name: Deploy and Seed Database

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Make sequelize-cli executable
      - name: Make sequelize-cli executable
        run: chmod +x ./node_modules/.bin/sequelize-cli

      # Step 5: Set to prod
      - name: Set environment to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # Step 6: Run migrations
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/sequelize-cli db:migrate

      # Step 7: Seed 
      - name: Seed the database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/sequelize-cli db:seed:all

