name: Deploy and Seed Database

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if using a different Node.js version

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Make sequelize-cli executable
      - name: Make sequelize-cli executable
        run: chmod +x ./node_modules/.bin/sequelize-cli

      # Step 5: Set environment to production
      - name: Set environment to production
        run: echo "NODE_ENV=production" >> $GITHUB_ENV

      # Step 6: Run migrations using sequelize-cli
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/sequelize-cli db:migrate

      # Step 7: Seed the database using sequelize-cli
      - name: Seed the database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: ./node_modules/.bin/sequelize-cli db:seed:all

